Add workflow step to check code coverage and upload when pushed to devlopment (#98)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -430,8 +430,8 @@ jobs:
           name: PKG-Coverage-Report
           path: profile.cov
 
-  upload_coverage:
-    name: Upload Coverage📊
+  parse_coverage:
+    name: Code Coverage
     runs-on: ubuntu-latest
     needs: [Example-Unit-Testing,CMD-Unit-Testing,PKG-Unit-Testing]
     steps:
@@ -449,6 +449,41 @@ jobs:
           awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./CMD-Test-Report/profile.cov > merged_profile.cov
           tail -n +2 ./Example-Test-Report/profile.cov >> merged_profile.cov
           tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
+          
+      - name: Parse code-coverage value
+        working-directory: artifacts
+        run: |
+          codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
+          codeCoverage=${codeCoverage%?}
+          echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
+          
+      - name: Check if code-coverage is greater than threshold
+        run: |
+          codeCoverage=${{ env.CODE_COVERAGE }}
+          codeCoverage=${codeCoverage%??}
+          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
+
+  upload_coverage:
+    name: Upload Coverage📊
+    runs-on: ubuntu-latest
+    needs: [Example-Unit-Testing,CMD-Unit-Testing,PKG-Unit-Testing]
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
+    steps:
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
+
+      - name: Download Coverage Report
+        uses: actions/download-artifact@v3
+        with:
+          path: artifacts
+
+      - name: Merge Coverage Files
+        working-directory: artifacts
+        run: |
+          awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./CMD-Test-Report/profile.cov > merged_profile.cov
+          tail -n +2 ./Example-Test-Report/profile.cov >> merged_profile.cov
+          tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
+
 
       - name: Upload
         uses: paambaati/codeclimate-action@v5.0.0
