Add tests for Logger Service & fix linters (#195)
* add tests for logger.go

* refactor tests

* add tests for service and logger packages

* fix tests

* updates tests for logger and service pkg

* update workflow yaml

* review changes

---------

Co-authored-by: Aryan Mehrotra <44036979+aryanmehrotra@users.noreply.github.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -61,19 +61,18 @@ jobs:
     name: PKG Unit Testing🛠
     runs-on: ubuntu-latest
     services:
+      redis:
+        image: redis:7.0.5
+        ports:
+          - "2002:6379"
+        options: "--entrypoint redis-server"
+
       mysql:
         image: mysql:8.2.0
         ports:
           - "2001:3306"
         env:
           MYSQL_ROOT_PASSWORD: "password"
-          MYSQL_DATABASE: "test"
-
-      redis:
-        image: redis:7.0.5
-        ports:
-          - "2002:6379"
-        options: "--entrypoint redis-server"
     steps:
       - name: Checkout code into go module directory
         uses: actions/checkout@v4
@@ -120,19 +119,19 @@ jobs:
         run: |
           awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
           tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
-          
+
       - name: Parse code-coverage value
         working-directory: artifacts
         run: |
           codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
           codeCoverage=${codeCoverage%?}
           echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
-          
-#      - name: Check if code-coverage is greater than threshold
-#        run: |
-#          codeCoverage=${{ env.CODE_COVERAGE }}
-#          codeCoverage=${codeCoverage%??}
-#          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
+
+  #      - name: Check if code-coverage is greater than threshold
+  #        run: |
+  #          codeCoverage=${{ env.CODE_COVERAGE }}
+  #          codeCoverage=${codeCoverage%??}
+  #          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
 
   upload_coverage:
     name: Upload Coverage📊
