comment one test

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -68,98 +68,98 @@ jobs:
           name: Example-Test-Report
           path: profile.cov
 
-#  PKG-Unit-Testing:
-#    name: PKG Unit Testing🛠
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - name: Checkout code into go module directory
-#        uses: actions/checkout@v4
-#        with:
-#          fetch-depth: 0
-#
-#      - name: Set up  Go 1.21
-#        uses: actions/setup-go@v4
-#        with:
-#          go-version: 1.21
-#        id: Go
-#
-#      - name: Get dependencies
-#        run: |
-#          go mod download
-#
-#      - name: Test
-#        run: |
-#          export GOFR_ENV=test
-#          go test gofr.dev/pkg/... -v -short -coverprofile profile.cov -coverpkg=gofr.dev/pkg/...
-#          go tool cover -func profile.cov
-#
-#      - name: Upload Test Coverage
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: PKG-Coverage-Report
-#          path: profile.cov
-#
-#  parse_coverage:
-#    name: Code Coverage
-#    runs-on: ubuntu-latest
-#    needs: [Example-Unit-Testing,PKG-Unit-Testing]
-#    steps:
-#      - name: Check out code into the Go module directory
-#        uses: actions/checkout@v4
-#
-#      - name: Download Coverage Report
-#        uses: actions/download-artifact@v3
-#        with:
-#          path: artifacts
-#
-#      - name: Merge Coverage Files
-#        working-directory: artifacts
-#        run: |
-#          awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
-#          tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
-#
-#      - name: Parse code-coverage value
-#        working-directory: artifacts
-#        run: |
-#          codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
-#          codeCoverage=${codeCoverage%?}
-#          echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
-#
-#        - name: Check if code-coverage is greater than threshold
-#          run: |
-#            codeCoverage=${{ env.CODE_COVERAGE }}
-#            codeCoverage=${codeCoverage%??}
-#            if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
-#
-#  upload_coverage:
-#    name: Upload Coverage📊
-#    runs-on: ubuntu-latest
-#    needs: [Example-Unit-Testing,PKG-Unit-Testing]
-#    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
-#    steps:
-#      - name: Check out code into the Go module directory
-#        uses: actions/checkout@v4
-#
-#      - name: Download Coverage Report
-#        uses: actions/download-artifact@v3
-#        with:
-#          path: artifacts
-#
-#      - name: Merge Coverage Files
-#        working-directory: artifacts
-#        run: |
-#          awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
-#          tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
-#
-#
-#      - name: Upload
-#        uses: paambaati/codeclimate-action@v5.0.0
-#        env:
-#          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
-#        with:
-#          coverageLocations: artifacts/merged_profile.cov:gocov
-#          prefix: gofr.dev
+  PKG-Unit-Testing:
+    name: PKG Unit Testing🛠
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code into go module directory
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up  Go 1.21
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.21
+        id: Go
+
+      - name: Get dependencies
+        run: |
+          go mod download
+
+      - name: Test
+        run: |
+          export GOFR_ENV=test
+          go test gofr.dev/pkg/... -v -short -coverprofile profile.cov -coverpkg=gofr.dev/pkg/...
+          go tool cover -func profile.cov
+
+      - name: Upload Test Coverage
+        uses: actions/upload-artifact@v3
+        with:
+          name: PKG-Coverage-Report
+          path: profile.cov
+
+  parse_coverage:
+    name: Code Coverage
+    runs-on: ubuntu-latest
+    needs: [Example-Unit-Testing,PKG-Unit-Testing]
+    steps:
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
+
+      - name: Download Coverage Report
+        uses: actions/download-artifact@v3
+        with:
+          path: artifacts
+
+      - name: Merge Coverage Files
+        working-directory: artifacts
+        run: |
+          awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
+          tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
+
+      - name: Parse code-coverage value
+        working-directory: artifacts
+        run: |
+         codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
+         codeCoverage=${codeCoverage%?}
+         echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
+
+      - name: Check if code-coverage is greater than threshold
+        run: |
+          codeCoverage=${{ env.CODE_COVERAGE }}
+          codeCoverage=${codeCoverage%??}
+          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
+
+  upload_coverage:
+    name: Upload Coverage📊
+    runs-on: ubuntu-latest
+    needs: [Example-Unit-Testing,PKG-Unit-Testing]
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
+    steps:
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
+
+      - name: Download Coverage Report
+        uses: actions/download-artifact@v3
+        with:
+          path: artifacts
+
+      - name: Merge Coverage Files
+        working-directory: artifacts
+        run: |
+          awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
+          tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
+
+
+      - name: Upload
+        uses: paambaati/codeclimate-action@v5.0.0
+        env:
+          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
+        with:
+          coverageLocations: artifacts/merged_profile.cov:gocov
+          prefix: gofr.dev
 
   code_quality:
     name: Code Quality🎖️
