undo unwanted changes

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,11 +29,6 @@ jobs:
           MYSQL_ROOT_PASSWORD: "password"
           MYSQL_DATABASE: "test"
 
-#      zipkin:
-#        image: openzipkin/zipkin:2
-#        ports:
-#          - 2005:9411
-
     steps:
       - name: Checkout code into go module directory
         uses: actions/checkout@v4
@@ -119,15 +114,15 @@ jobs:
       - name: Parse code-coverage value
         working-directory: artifacts
         run: |
-         codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
-         codeCoverage=${codeCoverage%?}
-         echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
+          codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
+          codeCoverage=${codeCoverage%?}
+          echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
 
-      - name: Check if code-coverage is greater than threshold
-        run: |
-          codeCoverage=${{ env.CODE_COVERAGE }}
-          codeCoverage=${codeCoverage%??}
-          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
+#      - name: Check if code-coverage is greater than threshold
+#        run: |
+#          codeCoverage=${{ env.CODE_COVERAGE }}
+#          codeCoverage=${codeCoverage%??}
+#          if [[ $codeCoverage -lt 92 ]]; then echo "code coverage cannot be less than 92%, currently its ${{ env.CODE_COVERAGE }}%" && exit 1; fi;
 
   upload_coverage:
     name: Upload Coverage📊
